# Docker Compose configuration file
#
# References:
#
# * Compose file version 3 reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/compose-file-v3/
#
# Copyright 2023 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
version: '3'

services:
  app:
    image: my-app:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=myapp
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myapp

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
